### ISSUE TITLE
训练的时候的内存爆炸问题

### ISSUE THREAD

**Issue by goutianrui** [BICLab/Spike-Driven-Transformer-V2#3]
在训练的过程中遇到训练内存不足的报错，报错如下：
Traceback (most recent call last):
  File "main_finetune.py", line 584, in <module>
    main(args)
  File "main_finetune.py", line 513, in main
    train_stats = train_one_epoch(
  File "F:\Spike-Driven-Transformer-V2-main\classification\engine_finetune.py", line 68, in train_one_epoch
    outputs = model(samples)
  File "D:\anaconda\envs\spikmetaformer\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anaconda\envs\spikmetaformer\lib\site-packages\torch\nn\parallel\distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "D:\anaconda\envs\spikmetaformer\lib\site-packages\torch\nn\parallel\distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "D:\anaconda\envs\spikmetaformer\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\Spike-Driven-Transformer-V2-main\classification\models.py", line 553, in forward
    x = self.forward_features(x)
  File "F:\Spike-Driven-Transformer-V2-main\classification\models.py", line 540, in forward_features
    x = blk(x)
  File "D:\anaconda\envs\spikmetaformer\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\Spike-Driven-Transformer-V2-main\classification\models.py", line 170, in forward
    x = self.bn1(self.conv1(self.lif1(x).flatten(0, 1))).reshape(T, B, 4 * C, H, W)
  File "D:\anaconda\envs\spikmetaformer\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anaconda\envs\spikmetaformer\lib\site-packages\spikingjelly\clock_driven\neuron.py", line 861, in forward
    self.v = self.v_seq[-1].clone()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 11.99 GiB total capacity; 23.58 GiB already allocated; 0 bytes free; 23.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
想请问两个问题：
1.遇到该问题有没有什么解决办法？
2.请问您们在训练的时候的硬件条件是什么呢？
期待您的回复，十分感激！

**Comment by goutianrui** [comment]
另外就是想问一下这个训练的时间是不是有点可怕，GPU是一块4070-12G，内存24G，第一次输出的训练时间是45天。[00:17:31.995481] Epoch: [0]  [    0/20018]  eta: 45 days, 10:25:28  lr: 0.000000  loss: 6.9995 (6.9995)  time: 196.0999  data: 19.9251  max mem: 22935
参数如下： 
Namespace(aa='rand-m9-mstd0.5-inc1',
accum_iter=1,
batch_size=64,
blr=0.0006,
clip_grad=None,
color_jitter=None,
cutmix=0,
cutmix_minmax=None,
data_path='../raid/ligq/imagenet1-k/',
device='cuda',
dist_backend='gloo',
dist_eval=True,
dist_on_itp=False,
dist_url='env://',
distillation_alpha=0.5,
distillation_tau=1.0,
distillation_type='none',
distributed=True,
drop_path=0.1,
epochs=200,
eval=False,
finetune='',
global_pool=True,
gpu=0,
input_size=224,
kd=False,
layer_decay=1.0,
local_rank=-1,
log_dir='outputs/T1',
lr=None,
min_lr=1e-06,
mixup=0,
mixup_mode='batch',
mixup_prob=1.0,
mixup_switch_prob=0.5,
model='metaspikformer_8_512',
model_mode='ms',
nb_classes=1000,
num_workers=10,
output_dir='outputs/T1',
pin_mem=True,
rank=0,
recount=1,
remode='pixel',
reprob=0.25,
resplit=False,
resume=None,
seed=0,
smoothing=0.1,
start_epoch=0,
teacher_model='caformer_b36_in21ft1k',
time_steps=1,
warmup_epochs=10,
weight_decay=0.05,
world_size=1)
请问这个应该如何调整呢

**Comment by goutianrui** [comment]
爆内存通过将batch_size减半已经能跑了，但是运行时间是问题

**Comment by jkhu29** [comment]
感谢您的关注。您所提出的问题与您先有硬件情况高度相关而与算法无关，具体的硬件可参考目前经典的Backbone文章，例如SwinTransformer、RMT等。

如果您对算法本身有其他疑问，欢迎重新打开该issue。
